server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://your-config-repo-url.git # 請改為實際 config-repo 位址
          search-paths: config-repo
          default-label: main
logging:
  level:
    root: INFO
    org.springframework.cloud.config: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
